function makeOutputPanelControls(pluginObj, parentHandle)

% params
spacing = 5;
padding = 5;
fontSize = pluginObj.fontSize;
fontHeight = pluginObj.fontHeight;

thisTag = pluginObj.panelTag('scrollingPanel');
scrollingPanel = uix.ScrollingPanel('Tag',thisTag, 'Parent',parentHandle);

panelVbox = uix.VBox('Parent',scrollingPanel, 'Spacing',spacing, 'Padding', padding);

makeTargetControls(panelVbox);

makeTargetNameControls(panelVbox);

makeDeleteSourceControls(panelVbox);

% set sizes
% controlHeight = fontHeight + spacing + padding;
controlHeight = 1.5*fontHeight + spacing;
vBoxHeights = [controlHeight*4, fontHeight*1.5, fontHeight*1.5];
set(panelVbox, 'Heights', vBoxHeights );
set(scrollingPanel, 'Heights', sum(vBoxHeights)+spacing*2+padding*2 );

%% Nested Fn
  function makeTargetControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % targetTypeLabel
    thisTag = pluginObj.panelTag('targetTypeLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Target Type:',...
      'Parent',thisHbox);

    thisTag = pluginObj.panelTag('targetRadioBox');
    thisVbox = uixVRadioBox( 'Parent', thisHbox, 'Spacing', spacing,...
      'Tag',thisTag, 'Callback',pluginObj.callbackHandle(thisTag));
    
    % mergeTarget
    thisTag = pluginObj.panelTag('mergeTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radiobutton',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Merge into Source Hypercube',...
      'UserData',pluginObj.userData,...
      'Parent',thisVbox);
    
    % newHcTarget
    thisTag = pluginObj.panelTag('newHcTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radiobutton',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','New Hypercube',...
      'UserData',pluginObj.userData,...
      'Parent',thisVbox);
    
    % workspaceTarget
    thisTag = pluginObj.panelTag('fileTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radiobutton',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Workspace Variable',...
      'UserData',pluginObj.userData,...
      'Parent',thisVbox);
    
    % fileTarget
    thisTag = pluginObj.panelTag('fileTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radiobutton',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','New File',...
      'UserData',pluginObj.userData,...
      'Parent',thisVbox);
    
    set(thisHbox, 'Widths',[-2 -3]);
  end

  function makeTargetNameControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % targetNameLabel
    thisTag = pluginObj.panelTag('targetNameLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.getTargetNameLabel(),...
      'Parent',thisHbox);
    
    % targetNameBox
    thisTag = pluginObj.panelTag('targetNameBox');
    uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set box size
    set(thisHbox, 'Widths',[-2 -3]);
  end

  function makeDeleteSourceControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % deleteSourceHcLabel
    thisTag = pluginObj.panelTag('deleteSourceHcLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Toggle Delete Source Hypercube:',...
      'Enable','off',...
      'Parent',thisHbox);
    
    % deleteSourceHcToggle
    thisTag = pluginObj.panelTag('deleteSourceHcToggle');
    uicontrol(...
      'Tag',thisTag,...
      'Style','togglebutton',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','(   )',...%sprintf('Delete Source Hypercube (%s)', char(hex2dec('2714'))),...
      'Value',0,...
      'Enable','off',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set box size
    set(thisHbox, 'Widths',[-2 -3]);
  end

end