function makeOutputPanelControls(pluginObj, parentHandle)

% params
spacing = 5;
padding = 5;
fontSize = pluginObj.fontSize;
fontHeight = pluginObj.fontHeight;

thisTag = pluginObj.panelTag('scrollingPanel');
scrollingPanel = uix.ScrollingPanel('Tag',thisTag, 'Parent',parentHandle);

panelVbox = uix.VBox('Parent',scrollingPanel, 'Spacing',spacing, 'Padding', padding);

makeTargetControls(panelVbox);

makeTargetNameControls(panelVbox);

makeDeleteSourceControls(panelVbox);

% set sizes
panelHeight = fontHeight + spacing + padding;
vBoxHeights = [panelHeight*3, fontHeight*2, fontHeight*2];
set(panelVbox, 'Heights', vBoxHeights );
set(scrollingPanel, 'Heights', sum(vBoxHeights)+spacing*2+padding*2 );

%% Nested Fn
  function makeTargetControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % targetTypeLabel
    thisTag = pluginObj.panelTag('targetTypeLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Target Type:',...
      'Parent',thisHbox);
    
    thisVbox = uix.VBox( 'Parent', thisHbox, 'Spacing', spacing);
    
    % mergeTarget
    thisTag = pluginObj.panelTag('mergeTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radio',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Merge',...
      'UserData',pluginObj.userData,...
      'Callback',@gvAnalysisPlugin.Callback_analysis_panel_targetRadio,...
      'Parent',thisVbox);
    
    % newHcTarget
    thisTag = pluginObj.panelTag('newHcTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radio',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','New Hypercube',...
      'UserData',pluginObj.userData,...
      'Callback',@gvAnalysisPlugin.Callback_analysis_panel_targetRadio,...
      'Parent',thisVbox);
    
    % fileTarget
    thisTag = pluginObj.panelTag('fileTargetRadio');
    uicontrol(...
      'Tag',thisTag,...
      'Style','radio',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','File',...
      'UserData',pluginObj.userData,...
      'Callback',@gvAnalysisPlugin.Callback_analysis_panel_targetRadio,...
      'Parent',thisVbox);
    
    set(thisHbox, 'Widths',[-2 -3]);
  end

  function makeTargetNameControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % targetNameLabel
    thisTag = pluginObj.panelTag('targetNameLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Target Name:',...
      'Parent',thisHbox);
    
    % targetNameBox
    thisTag = pluginObj.panelTag('targetNameBox');
    uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set box size
    set(thisHbox, 'Widths',[-2 -3]);
  end

  function makeDeleteSourceControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    % deleteSourceHcLabel
    thisTag = pluginObj.panelTag('deleteSourceHcLabel');
    uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Delete Source Hypercube:',...
      'Enable','off',...
      'Parent',thisHbox);
    
    % deleteSourceHcToggle
    thisTag = pluginObj.panelTag('deleteSourceHcToggle');
    uicontrol(...
      'Tag',thisTag,...
      'Style','togglebutton',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','( )',...%sprintf('Delete Source Hypercube (%s)', char(hex2dec('2714'))),...
      'Value',0,...
      'Enable','off',...
      'Parent',thisHbox);
    
    % Set box size
    set(thisHbox, 'Widths',[-2 -3]);
  end

end