function createHypercubePanelControls(pluginObj, parentHandle)
%% createHypercubePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
panelTitleFontSize = fontSize;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

% mainData panel
mainDataPanel = uix.Panel(...
  'Tag','mainDataPanel',...
  'Parent',parentHandle,...
  'Title','Data',...
  'FontUnits','points',...
  'FontSize',panelTitleFontSize...
);

hypercubeHbox = uix.HBox('Parent',mainDataPanel, 'Spacing',spacing, 'Padding',padding);

% activeHyperCubeLabel
uiControlsHandles.activeHyperCubeLabel = uicontrol(...
  'Tag','activeHyperCubeLabel',...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Active Hypercube:',...
  'Parent',hypercubeHbox);

% hypercubeMenu
uiControlsHandles.hypercubeMenu = uicontrol(...
  'Tag','hypercubeMenu',...
  'Style','popupmenu',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Default Hypercube',...
  'Value',1,...
  'Callback',@(hObject,eventdata)gvMainWindow_export('hypercubeMenu_Callback',hObject,eventdata,guidata(hObject)),...
  'Parent',hypercubeHbox);

% Store Handles
% pluginObj.handles.hypercubePanel.controls = uiControlsHandles;

end
