function makeFig(pluginObj)

mainWindowHandle = figure(...
  'Units','pixels',...
  'Position',[29 778 567 567],...
  'MenuBar','none',...
  'Name',pluginObj.windowName,...
  'NumberTitle','off',...
  'Tag',pluginObj.figTag(),...
  'UserData',pluginObj.userData,...
  'CloseRequestFcn',@pluginObj.Callback_closeRequestFcn...
);

% Set Handle
pluginObj.handles.fig = mainWindowHandle;

end
