function makeHypercubePanelControls(pluginObj, parentHandle)
%% makeHypercubePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
panelTitleFontSize = fontSize;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

% mainData panel
mainDataPanel = uix.Panel(...
  'Tag','mainDataPanel',...
  'Parent',parentHandle,...
  'Title','Data',...
  'FontUnits','points',...
  'FontSize',panelTitleFontSize...
);

hypercubeHbox = uix.HBox('Parent',mainDataPanel, 'Spacing',spacing, 'Padding',padding);

% activeHyperCubeText
uiControlsHandles.activeHypercubeText= uicontrol(...
  'Tag','activeHypercubeText',...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Active Hypercube:',...
  'Parent',hypercubeHbox);

% hypercubeMenu
menuStr = fieldnames(orderfields(pluginObj.controller.model.data));
activeHypercubeName = pluginObj.controller.view.activeHypercubeName;
menuValue = find( strcmp( menuStr, activeHypercubeName ) );

if isempty(menuStr)
  menuStr = {'[None]'};
  menuValue = 1;
end

uiControlsHandles.hypercubeMenu = uicontrol(...
  'Tag','hypercubeMenu',...
  'Style','popupmenu',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String',menuStr,...
  'Value',menuValue,...
  'UserData',pluginObj.userData,...
  'Callback',@gvMainWindowPlugin.Callback_activeHyperCubeMenu,...
  'Parent',hypercubeHbox);

set(hypercubeHbox, 'Widths',[-1, -1])

% Store Handles
% pluginObj.handles.hypercubePanel.controls = uiControlsHandles;

end
