function panelHandle = makePanelControls(pluginObj, parentHandle)
%% makePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
fontHeight = pluginObj.fontHeight;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

thisTag = pluginObj.panelTag('imagePanel');
imagePanel = uix.Panel(...
  'Tag',thisTag,...
  'Parent',parentHandle,...
  'Title','Image Window',...
  'FontUnits','points',...
  'FontSize',fontSize...
);

mainVbox = uix.VBox('Parent',imagePanel, 'Spacing',spacing, 'Padding',padding);

uiControlsHandles.parent = mainVbox;

% Row 1
% openImageButton
thisTag = pluginObj.panelTag('openWindowButton');
uiControlsHandles.openImageButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Open Image',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);

% Row 2
makeImageDirPathControls(mainVbox);

% Row 3
makeImageTypeControls(mainVbox);

panelHeight = fontHeight*2 + spacing + padding;
set(mainVbox, 'Heights',[panelHeight, panelHeight, panelHeight])

%% argout
panelHandle = uiControlsHandles;


%% Nested fn
  function makeImageTypeControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % imageTypeLabel
    thisTag = pluginObj.panelTag('imageTypeLabel');
    uiControlsHandles.imageTypeLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Type:',...
      'Parent',thisHbox);
    
    
    % imageTypeMenu
    thisTag = pluginObj.panelTag('imageTypeMenu');
    uiControlsHandles.imageTypeMenu = uicontrol(...
      'Tag',thisTag,...
      'Style','popupmenu',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.getImageTypes(),...
      'Value',1,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
      set(thisHbox, 'Widths',[-1 -3]);
  end


  function makeImageDirPathControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % imageDirLabel
    thisTag = pluginObj.panelTag('imageDirLabel');
    uiControlsHandles.imagePathLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Image Dir:',...
      'Parent',thisHbox);
    
    
    % imageDirBox
    thisTag = pluginObj.panelTag('imageDirBox');
    uiControlsHandles.delayValueBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.controller.app.config.defaultImagePath,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    set(thisHbox, 'Widths',[-1 -3]);
  end
end
