function panelHandle = makePanelControls(pluginObj, parentHandle)
%% makePanelControls
%
% Input: parentHandle - handle for uicontrol parent

% get current stack val
currVal = pluginObj.view.dynamic.dsPlotStackVal;

% get stack box strings
if size(pluginObj.metadata.stack, 1) > 0
  funcTagBoxStr = pluginObj.metadata.stack{currVal, 1};
  funcBoxStr = pluginObj.metadata.stack{currVal, 2};
  funcOptsBoxStr = pluginObj.metadata.stack{currVal, 3};
else
  funcBoxStr = '';
  funcOptsBoxStr = '';
end

fontSize = pluginObj.fontSize;
fontHeight = pluginObj.fontHeight;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

thisTag = pluginObj.panelTag('dsPlotPanel');
imagePanel = uix.Panel(...
  'Tag',thisTag,...
  'Parent',parentHandle,...
  'Title','DS Plot Window',...
  'FontUnits','points',...
  'FontSize',fontSize...
);

mainVbox = uix.VBox('Parent',imagePanel, 'Spacing',spacing, 'Padding',padding);

uiControlsHandles.parent = mainVbox;

nRows = 0;

% Row 1
% openWindowButton
thisTag = pluginObj.panelTag('openWindowButton');
uiControlsHandles.openDsPlotButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Open dsPlot Window',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);
nRows = nRows + 1;

% Row 2
% importDataButton
thisTag = pluginObj.panelTag('importDataButton');
uiControlsHandles.importDataButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Import All DS Data',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);
nRows = nRows + 1;

% Row 3
makeFuncTagControls(mainVbox);
nRows = nRows + 1;

% Row 4
makeFuncControls(mainVbox);
nRows = nRows + 1;

% Row 5
makeFuncOptsControls(mainVbox);
nRows = nRows + 1;

% Row 6
makeStackControls(mainVbox);
nRows = nRows + 1;

% Row 7
makeModeControls(mainVbox);
nRows = nRows + 1;

% Row 8
% deleteDataButton
thisTag = pluginObj.panelTag('deleteDataButton');
uiControlsHandles.importDataButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Delete All DS Data',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);
nRows = nRows + 1;

panelHeight = fontHeight*2 + spacing + padding;
set(mainVbox, 'Heights',panelHeight*ones(1,nRows))

%% argout
panelHandle = uiControlsHandles;

%% notify listener
notify(pluginObj, 'panelControlsMade');


%% Nested fn
  function makeFuncTagControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % funcTagLabel
    thisTag = pluginObj.panelTag('funcTagLabel');
    uiControlsHandles.funcLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Stack Label:',...
      'Parent',thisHbox);
    
    
    % funcTagBox
    thisTag = pluginObj.panelTag('funcTagBox');
    uiControlsHandles.funcBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',funcTagBoxStr,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
      set(thisHbox, 'Widths',[-1 -3]);
  end


  function makeFuncControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % funcLabel
    thisTag = pluginObj.panelTag('funcLabel');
    uiControlsHandles.funcLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Plot Function:',...
      'Parent',thisHbox);
    
    
    % funcBox
    thisTag = pluginObj.panelTag('funcBox');
    uiControlsHandles.funcBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'FontName','Monospaced',...
      'String',funcBoxStr,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
      set(thisHbox, 'Widths',[-1 -3]);
  end


  function makeFuncOptsControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % funcOptsLabel
    thisTag = pluginObj.panelTag('funcOptsLabel');
    uiControlsHandles.funcOptsLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Function Options:',...
      'Parent',thisHbox);
    
    
    % funcOptsBox
    thisTag = pluginObj.panelTag('funcOptsBox');
    uiControlsHandles.funcOptsBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'FontName','Monospaced',...
      'String',funcOptsBoxStr,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    set(thisHbox, 'Widths',[-1 -3]);
  end


  function makeStackControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing, 'Padding',padding);
    
    % stackLabel
    thisTag = pluginObj.panelTag('stackLabel');
    uiControlsHandles.markerTypeLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Function Stack:',...
      'Parent',thisHbox);
    
    
    % stackMenu
    stackVal = pluginObj.view.dynamic.dsPlotStackVal;
    thisTag = pluginObj.panelTag('stackMenu');
    uiControlsHandles.markerTypeMenu = uicontrol(...
      'Tag',thisTag,...
      'Style','popupmenu',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.stackStr(),...
      'Value',stackVal,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % pushStackButton
    thisTag = pluginObj.panelTag('pushStackButton');
    uiControlsHandles.importDataButton = uicontrol(...
      'Tag',thisTag,...
      'Style','pushbutton',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','+',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % popStackButton
    thisTag = pluginObj.panelTag('popStackButton');
    uiControlsHandles.importDataButton = uicontrol(...
      'Tag',thisTag,...
      'Style','pushbutton',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','-',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set row2hBox Widths
    set(thisHbox, 'Widths',[-3 -7, -1, -1]);
  end


  function makeModeControls(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing, 'Padding',padding);
    
    % modeLabel
    thisTag = pluginObj.panelTag('modeLabel');
    uiControlsHandles.markerTypeLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Import Mode:',...
      'Parent',thisHbox);
    
    
    % modeMenu
    modeVal = pluginObj.view.dynamic.dsPlotModeVal;
    thisTag = pluginObj.panelTag('modeMenu');
    uiControlsHandles.markerTypeMenu = uicontrol(...
      'Tag',thisTag,...
      'Style','popupmenu',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.importModes,...
      'Value',modeVal,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set row2hBox Widths
    set(thisHbox, 'Widths',[-1 -3]);
  end
end
