function panelHandle = makePanelControls(pluginObj, parentHandle)
%% makePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
fontHeight = pluginObj.fontHeight;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

thisTag = pluginObj.panelTag('dsPlotPanel');
imagePanel = uix.Panel(...
  'Tag',thisTag,...
  'Parent',parentHandle,...
  'Title','DS Plot Window',...
  'FontUnits','points',...
  'FontSize',fontSize...
);

mainVbox = uix.VBox('Parent',imagePanel, 'Spacing',spacing, 'Padding',padding);

uiControlsHandles.parent = mainVbox;

% Row 1
% openWindowButton
thisTag = pluginObj.panelTag('openWindowButton');
uiControlsHandles.openDsPlotButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Open dsPlot Window',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);

% Row 2
% importDataButton
thisTag = pluginObj.panelTag('importDataButton');
uiControlsHandles.importDataButton = uicontrol(...
  'Tag',thisTag,...
  'Style','pushbutton',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'String','Import All DS Data',...
  'UserData',pluginObj.userData,...
  'Callback',pluginObj.callbackHandle(thisTag),...
  'Parent',mainVbox);

% Row 3
makeFuncControls(mainVbox);

% Row 4
makeFuncOptsControls(mainVbox);

panelHeight = fontHeight*2 + spacing + padding;
set(mainVbox, 'Heights',[panelHeight, panelHeight, panelHeight, panelHeight])

%% argout
panelHandle = uiControlsHandles;

%% notify listener
notify(pluginObj, 'panelControlsMade');


%% Nested fn
  function makeFuncControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % funcLabel
    thisTag = pluginObj.panelTag('funcLabel');
    uiControlsHandles.funcLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Plot Function:',...
      'Parent',thisHbox);
    
    
    % funcBox
    thisTag = pluginObj.panelTag('funcBox');
    uiControlsHandles.funcBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',pluginObj.metadata.plotFn,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
      set(thisHbox, 'Widths',[-1 -3]);
  end


  function makeFuncOptsControls(parentHandle)
    thisHbox = uix.HBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);
    
    % funcOptsLabel
    thisTag = pluginObj.panelTag('funcOptsLabel');
    uiControlsHandles.funcOptsLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Function Options:',...
      'Parent',thisHbox);
    
    
    % funcOptsBox
    thisTag = pluginObj.panelTag('funcOptsBox');
    uiControlsHandles.funcOptsBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    set(thisHbox, 'Widths',[-1 -3]);
  end
end
