function createHypercubePanelControls(viewObj, parentHandle)
%% createHypercubePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = viewObj.fontSize;
% spacing = 2; % px
% padding = 2; % px

uiControlsHandles = struct();

uiControlsHandles.hypercubeMenu = uicontrol(...
'Tag','hypercubeMenu',...
'Style','popupmenu',...
'FontUnits','points',...
'FontSize',fontSize,...
'String','Default Hypercube',...
'Value',1,...
'Callback',@(hObject,eventdata)gvMainWindow_export('hypercubeMenu_Callback',hObject,eventdata,guidata(hObject)),...
'Parent',parentHandle);

% Store Handles
viewObj.mainWindow.hypercubePanel.controlHandles = uiControlsHandles;

end
