function createImagePanelControls(windowObj, parentHandle)
%% createImagePanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = windowObj.fontSize;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

vBox = uix.VBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);

% vbox Row 1
row1hBox = uix.HBox('Parent',vBox, 'Spacing',spacing);
makeRow1Hbox(row1hBox);

% vbox Row 2
uix.Empty('Parent', vBox);

% Store Handles
windowObj.handles.imagePanel.controls = uiControlsHandles;


%% Nested fn
  function makeRow1Hbox(hBox)
    % openImageButton
    uiControlsHandles.openImageButton = uicontrol(...
      'Tag','openImageButton',...
      'Style','pushbutton',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Open Image',...
      'Callback',@(hObject,eventdata)gvMainWindow_export('imageButton_Callback',hObject,eventdata,guidata(hObject)),...
      'Parent',hBox);
    
    
    % imageTypeLabel
    uiControlsHandles.imageTypeLabel = uicontrol(...
      'Tag','imageTypeLabel',...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Type:',...
      'Parent',hBox);
    
    
    % imageTypeMenu
    uiControlsHandles.imageTypeMenu = uicontrol(...
      'Tag','imageTypeMenu',...
      'Style','popupmenu',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','ImageType',...
      'Value',1,...
      'Callback',@(hObject,eventdata)gvMainWindow_export('imageTypeMenu_Callback',hObject,eventdata,guidata(hObject)),...
      'Parent',hBox);
    
      set(hBox, 'Widths',[-2 -1 -3]);
  end
end
