function createMainWindowFig(viewObj)

mainWindowHandle = figure(...
  'PaperUnits',get(0,'defaultfigurePaperUnits'),...
  'Units','centimeters',...
  'Position',[1 40 20 20],...
  'Visible',get(0,'defaultfigureVisible'),...
  'Color',get(0,'defaultfigureColor'),...
  'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
  'CurrentAxesMode','manual',...
  'CurrentObjectMode','manual',...
  'CurrentPointMode','manual',...
  'SelectionTypeMode','manual',...
  'ResizeFcn','',...
  'IntegerHandle',get(0,'defaultfigureIntegerHandle'),...
  'NextPlot',get(0,'defaultfigureNextPlot'),...
  'Alphamap',get(0,'defaultfigureAlphamap'),...
  'WindowButtonDownFcn','',...
  'WindowButtonUpFcn','',...
  'WindowButtonMotionFcn','',...
  'WindowScrollWheelFcn','',...
  'WindowKeyPressFcn','',...
  'WindowKeyReleaseFcn','',...
  'MenuBar','none',...
  'ToolBar',get(0,'defaultfigureToolBar'),...
  'Pointer',get(0,'defaultfigurePointer'),...
  'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
  'Name','GIMBL-Vis Toolbox',...
  'NumberTitle','off',...
  'ButtonDownFcn','',...
  'CreateFcn', '',...
  'DeleteFcn','',...
  'Tag','figure1',...
  'UserData',[],...
  'WindowStyle',get(0,'defaultfigureWindowStyle'),...
  'DockControls',get(0,'defaultfigureDockControls'),...
  'Resize',get(0,'defaultfigureResize'),...
  'PaperPosition',get(0,'defaultfigurePaperPosition'),...
  'PaperSize',get(0,'defaultfigurePaperSize'),...
  'PaperType',get(0,'defaultfigurePaperType'),...
  'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
  'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
  'ScreenPixelsPerInchMode','manual',...
  'KeyPressFcn','',...
  'KeyReleaseFcn','',...
  'HandleVisibility',get(0,'defaultfigureHandleVisibility')...
);

% Set Handle
viewObj.mainWindow.handle = mainWindowHandle;

end