function createFig(windowObj)

mainWindowHandle = figure(...
  'Units','pixels',...
  'Position',[29 778 567 567],...
  'MenuBar','none',...
  'Name','GIMBL-Vis Toolbox',...
  'NumberTitle','off',...
  'Tag','figure1',...
  'UserData',windowObj.userData...
);

% Set Handle
windowObj.handles.fig = mainWindowHandle;

end