function makePlotPanelControls(pluginObj, parentHandle)
%% makePlotPanelControls
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

% Make 2x2 grid
grid2x2 = uix.Grid('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);

% (1,1)
% openPlotButton
thisTag = pluginObj.panelTag('openPlotButton');
uiControlsHandles.openPlotButton = uicontrol(...
'Tag',thisTag,...
'Style','pushbutton',...
'FontUnits','points',...
'FontSize',fontSize,...
'String','Open Plot',...
'UserData',pluginObj.userData,...
'Callback',@gvPlotWindowPlugin.openWindowCallback,...
'Parent',grid2x2);

% (2,1)
% iterateToggle
thisTag = pluginObj.panelTag('iterateToggle');
uiControlsHandles.iterateToggle = uicontrol(...
'Tag',thisTag,...
'Style','togglebutton',...
'FontUnits','points',...
'FontSize',fontSize,...
'String','Iterate',...
'UserData',pluginObj.userData,...
'Callback',pluginObj.callbackHandle(thisTag),...
'Parent',grid2x2);

% Change iterateToggle String
set(uiControlsHandles.iterateToggle, 'String', sprintf('Iterate ( %s )', char(9654))); %start char (arrow)

% (1,2)
% openLegendButton
thisTag = pluginObj.panelTag('openLegendButton');
uiControlsHandles.openLegendButton = uicontrol(...
'Tag',thisTag,...
'Style','pushbutton',...
'FontUnits','points',...
'FontSize',fontSize,...
'String','Show Legend',...
'UserData',pluginObj.userData,...
'Callback',pluginObj.callbackHandle(thisTag),...
'Parent',grid2x2);

% (2,2)
% Use Hbox for delay
delayHbox = uix.HBox('Parent',grid2x2, 'Spacing',spacing, 'Padding',padding);
makeDelayHbox(delayHbox);

% Set layout sizes
set(grid2x2, 'Heights',[-1 -1], 'Widths',[-1 -1]);

% Store Handles
% pluginObj.handles.plotPanel.controls = uiControlsHandles;


%% Nested fn
  function makeDelayHbox(delayHbox)
    % delayLabel
    thisTag = pluginObj.panelTag('delayLabel');
    uiControlsHandles.delayLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','Delay [s]:',...
      'Parent',delayHbox);
    
    
    % delayValueBox
    thisTag = pluginObj.panelTag('delayValueBox');
    uiControlsHandles.delayValueBox = uicontrol(...
      'Tag',thisTag,...
      'Style','edit',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','0.5',...
      'Value',0.5,...
      'UserData',pluginObj.userData,...
      'Callback',@gvPlotWindowPlugin.delayEditCallback,...
      'Parent',delayHbox);
    
      set(delayHbox, 'Widths',[-3, -1.3])
  end

end
