function makePlotMarkerPanelControls(pluginObj, parentHandle)
%% makePlotMarkerPanelControls
%
% Input: parentHandle - handle for uicontrol parent

markerDefaultSize = 16;
markerMinSize = 2;
markerMaxSize = 500;

plot2dTypes = pluginObj.plot2dTypes;

plot3dTypes = pluginObj.plot3dTypes;

fontSize = pluginObj.fontSize;

spacing = 2; % px
padding = 2; % px

uiControlsHandles = struct();

vBox = uix.VBox('Parent',parentHandle, 'Spacing',spacing, 'Padding',padding);

% Row 1
makeRow1hBox(vBox);

% Row 2
makeRow2hBox(vBox);

% Row 3
makeRow3hBox(vBox);

% Set vBox Heights
set(vBox, 'Heights',[-1.2 -1 -1]);


%% Nested fn
  function makeRow1hBox(parentHandle)
    thisHbox = uix.HBox('Parent', parentHandle, 'Spacing', spacing);
    
    % autoSizeToggle
    thisTag = pluginObj.panelTag('autoSizeToggle');
    uiControlsHandles.autoSizeMarkerLabel = uicontrol(...
      'Tag',thisTag,...    
      'Style','togglebutton',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',sprintf('AutoSize (%s)', char(hex2dec('2714'))),...
      'Value',1,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % markerSizeSlider
    thisTag = pluginObj.panelTag('markerSizeSlider');
    tooltipStr = 'Hint: change slider with scroll wheel';
    uiControlsHandles.markerSizeSlider = uicontrol(...
      'Tag',thisTag,...
      'Style','slider',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'Min',markerMinSize,...
      'Max',markerMaxSize,...
      'Value',markerDefaultSize,...
      'SliderStep',get(0,'defaultuicontrolSliderStep'),...
      'Enable', 'off',...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'TooltipString', tooltipStr,...
      'Parent',thisHbox);
    
    % Set Box Widths
    set(thisHbox, 'Widths',[-2 -3]);
  end


  function makeRow2hBox(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    tooltipStr = 'Hint: change 2D Plot Type by pressing the "2" key';
    
    % plot2dTypeLabel
    thisTag = pluginObj.panelTag('plot2dTypeLabel');
    uiControlsHandles.plot2dTypeLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...    
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','2D Plot Type:',...
      'TooltipString', tooltipStr,...
      'Parent',thisHbox);
    
    
    % plot2dTypeMenu
    markerVal = pluginObj.view.dynamic.plot2dTypeVal;
    thisTag = pluginObj.panelTag('plot2dTypeMenu');
    uiControlsHandles.plot2dTypeMenu = uicontrol(...
      'Tag',thisTag,...
      'Style','popupmenu',...  
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',plot2dTypes,...
      'Value',markerVal,...
      'TooltipString', tooltipStr,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set row2hBox Widths
    set(thisHbox, 'Widths',[-2 -3]);
  end


  function makeRow3hBox(parentHandle)
    thisHbox = uix.HBox( 'Parent', parentHandle, 'Spacing', spacing);
    
    tooltipStr = 'Hint: change 3D Plot Type by pressing the "3" key';
    
    % plot3dTypeLabel
    thisTag = pluginObj.panelTag('plot3dTypeLabel');
    uiControlsHandles.plot2dTypeLabel = uicontrol(...
      'Tag',thisTag,...
      'Style','text',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String','3D Plot Type:',...
      'TooltipString', tooltipStr,...
      'Parent',thisHbox);
    
    
    % plot3dTypeMenu
    markerVal = pluginObj.view.dynamic.plot3dTypeVal;
    thisTag = pluginObj.panelTag('plot3dTypeMenu');
    uiControlsHandles.plot2dTypeMenu = uicontrol(...
      'Tag',thisTag,...
      'Style','popupmenu',...
      'FontUnits','points',...
      'FontSize',fontSize,...
      'String',plot3dTypes,...
      'Value',markerVal,...
      'TooltipString', tooltipStr,...
      'UserData',pluginObj.userData,...
      'Callback',pluginObj.callbackHandle(thisTag),...
      'Parent',thisHbox);
    
    % Set row2hBox Widths
    set(thisHbox, 'Widths',[-2 -3]);
  end

end
