function makeDataPanelTitles(pluginObj, parentHandle)
%% makeDataPanelTitles
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
titleFontWeight = 'bold';

fontWidth = pluginObj.fontWidth;

padding = 5; % px

dataTitlesHbox = uix.HBox('Parent',parentHandle, 'Padding', padding);

uiControlsHandles = struct();

% varTitle
thisTag = pluginObj.panelTag('varTitle');
uiControlsHandles.varTitle = uicontrol(...
  'Tag',thisTag,...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'FontWeight',titleFontWeight,...
  'String','Dims',...
  'Value',get(0,'defaultuicontrolValue'),...
  'Parent',dataTitlesHbox);

% valueTitle
thisTag = pluginObj.panelTag('valueTitle');
uiControlsHandles.valueTitle = uicontrol(...
  'Tag',thisTag,...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'FontWeight',titleFontWeight,...
  'String','Value',...
  'Parent',dataTitlesHbox);

uix.Empty('Parent',dataTitlesHbox);

% viewTitle
thisTag = pluginObj.panelTag('viewTitle');
uiControlsHandles.viewTitle = uicontrol(...
  'Tag',thisTag,...
  'Style','text',...
  'FontUnits','points',...
  'FontWeight',titleFontWeight,...
  'String','View',...
  'FontSize',fontSize,...
  'Parent',dataTitlesHbox);

% lockTitle
thisTag = pluginObj.panelTag('lockTitle');
uiControlsHandles.lockTitle = uicontrol(...
  'Tag',thisTag,...
  'Style','text',...
  'FontUnits','points',...
  'FontWeight',titleFontWeight,...
  'String','Lock',...
  'FontSize',fontSize,...
  'Parent',dataTitlesHbox);

set(dataTitlesHbox, 'Widths',[-5,-6,-2.5,fontWidth*8,fontWidth*8]);

end
