function makeDataPanelTitles(pluginObj, parentHandle)
%% makeDataPanelTitles
%
% Input: parentHandle - handle for uicontrol parent

fontSize = pluginObj.fontSize;
titleFontWeight = 'bold';

fontWidth = pluginObj.fontWidth;

padding = 5; % px

dataTitlesHbox = uix.HBox('Parent',parentHandle, 'Padding', padding);

uiControlsHandles = struct();

% varTitle
thisTagStr = 'varTitle';
uiControlsHandles.varTitle = uicontrol(...
  'Tag',[pluginObj.pluginFieldName '_panel_' thisTagStr],...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'FontWeight',titleFontWeight,...
  'String','Variables',...
  'Value',get(0,'defaultuicontrolValue'),...
  'Parent',dataTitlesHbox);

% valueTitle
thisTagStr = 'valueTitle';
uiControlsHandles.valueTitle = uicontrol(...
  'Tag',[pluginObj.pluginFieldName '_panel_' thisTagStr],...
  'Style','text',...
  'FontUnits','points',...
  'FontSize',fontSize,...
  'FontWeight',titleFontWeight,...
  'String','Value',...
  'Parent',dataTitlesHbox);

uix.Empty('Parent',dataTitlesHbox);

% viewTitle
thisTagStr = 'viewTitle';
uiControlsHandles.viewTitle = uicontrol(...
  'Tag',[pluginObj.pluginFieldName '_panel_' thisTagStr],...
  'Style','text',...
  'FontUnits','points',...
  'FontWeight',titleFontWeight,...
  'String','View',...
  'FontSize',fontSize,...
  'Parent',dataTitlesHbox);

% lockTitle
thisTagStr = 'lockTitle';
uiControlsHandles.lockTitle = uicontrol(...
  'Tag',[pluginObj.pluginFieldName '_panel_' thisTagStr],...
  'Style','text',...
  'FontUnits','points',...
  'FontWeight',titleFontWeight,...
  'String','Lock',...
  'FontSize',fontSize,...
  'Parent',dataTitlesHbox);

set(dataTitlesHbox, 'Widths',[-5,-6,-2.5,fontWidth*8,fontWidth*8])

% Store Handles
% pluginObj.handles.dataPanel.controls = uiControlsHandles;

end
